/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Type__3 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'pdfUrl' : IDL.Text,
});
export const Type__2 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'dayNumber' : IDL.Nat,
});
export const Type__1 = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Type = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'scheduledDate' : Time,
  'description' : IDL.Text,
  'zoomLink' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEbook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createGeopoliticsLesson' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createMasterclass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createZoomMeeting' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
  'deleteEbook' : IDL.Func([IDL.Nat], [], []),
  'deleteGeopoliticsLesson' : IDL.Func([IDL.Nat], [], []),
  'deleteMasterclass' : IDL.Func([IDL.Nat], [], []),
  'deleteZoomMeeting' : IDL.Func([IDL.Nat], [], []),
  'enrollInMasterclass' : IDL.Func([IDL.Nat], [], []),
  'getAllEbooks' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
  'getAllGeopoliticsLessons' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
  'getAllMasterclasses' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
  'getAllZoomMeetings' : IDL.Func([], [IDL.Vec(Type)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEbook' : IDL.Func([IDL.Nat], [Type__3], ['query']),
  'getGeopoliticsLesson' : IDL.Func([IDL.Nat], [Type__2], ['query']),
  'getMasterclass' : IDL.Func([IDL.Nat], [Type__1], ['query']),
  'getUserEnrollments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getZoomMeeting' : IDL.Func([IDL.Nat], [Type], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateEbook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGeopoliticsLesson' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Nat],
      [],
      [],
    ),
  'updateMasterclass' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateZoomMeeting' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Type__3 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'pdfUrl' : IDL.Text,
  });
  const Type__2 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'dayNumber' : IDL.Nat,
  });
  const Type__1 = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Type = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'scheduledDate' : Time,
    'description' : IDL.Text,
    'zoomLink' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEbook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createGeopoliticsLesson' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createMasterclass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createZoomMeeting' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'deleteEbook' : IDL.Func([IDL.Nat], [], []),
    'deleteGeopoliticsLesson' : IDL.Func([IDL.Nat], [], []),
    'deleteMasterclass' : IDL.Func([IDL.Nat], [], []),
    'deleteZoomMeeting' : IDL.Func([IDL.Nat], [], []),
    'enrollInMasterclass' : IDL.Func([IDL.Nat], [], []),
    'getAllEbooks' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
    'getAllGeopoliticsLessons' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
    'getAllMasterclasses' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
    'getAllZoomMeetings' : IDL.Func([], [IDL.Vec(Type)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEbook' : IDL.Func([IDL.Nat], [Type__3], ['query']),
    'getGeopoliticsLesson' : IDL.Func([IDL.Nat], [Type__2], ['query']),
    'getMasterclass' : IDL.Func([IDL.Nat], [Type__1], ['query']),
    'getUserEnrollments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getZoomMeeting' : IDL.Func([IDL.Nat], [Type], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateEbook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGeopoliticsLesson' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Nat],
        [],
        [],
      ),
    'updateMasterclass' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateZoomMeeting' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };