/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Type {
  'id' : bigint,
  'title' : string,
  'scheduledDate' : Time,
  'description' : string,
  'zoomLink' : string,
}
export interface Type__1 {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'instructor' : string,
  'description' : string,
  'price' : bigint,
}
export interface Type__2 {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'dayNumber' : bigint,
}
export interface Type__3 {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'author' : string,
  'pdfUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEbook' : ActorMethod<[string, string, string, string], bigint>,
  'createGeopoliticsLesson' : ActorMethod<
    [string, string, Time, bigint],
    bigint
  >,
  'createMasterclass' : ActorMethod<[string, string, string, bigint], bigint>,
  'createZoomMeeting' : ActorMethod<[string, string, string, Time], bigint>,
  'deleteEbook' : ActorMethod<[bigint], undefined>,
  'deleteGeopoliticsLesson' : ActorMethod<[bigint], undefined>,
  'deleteMasterclass' : ActorMethod<[bigint], undefined>,
  'deleteZoomMeeting' : ActorMethod<[bigint], undefined>,
  'enrollInMasterclass' : ActorMethod<[bigint], undefined>,
  'getAllEbooks' : ActorMethod<[], Array<Type__3>>,
  'getAllGeopoliticsLessons' : ActorMethod<[], Array<Type__2>>,
  'getAllMasterclasses' : ActorMethod<[], Array<Type__1>>,
  'getAllZoomMeetings' : ActorMethod<[], Array<Type>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEbook' : ActorMethod<[bigint], Type__3>,
  'getGeopoliticsLesson' : ActorMethod<[bigint], Type__2>,
  'getMasterclass' : ActorMethod<[bigint], Type__1>,
  'getUserEnrollments' : ActorMethod<[Principal], Array<bigint>>,
  'getZoomMeeting' : ActorMethod<[bigint], Type>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateEbook' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateGeopoliticsLesson' : ActorMethod<
    [bigint, string, string, Time, bigint],
    undefined
  >,
  'updateMasterclass' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateZoomMeeting' : ActorMethod<
    [bigint, string, string, string, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];