/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Type__3 {
    id: bigint;
    title: string;
    description: string;
    author: string;
    pdfUrl: string;
}
export interface Type__1 {
    id: bigint;
    title: string;
    duration: bigint;
    instructor: string;
    description: string;
    price: bigint;
}
export interface Type {
    id: bigint;
    title: string;
    scheduledDate: Time;
    description: string;
    zoomLink: string;
}
export type Time = bigint;
export interface Type__2 {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    dayNumber: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEbook(title: string, description: string, author: string, pdfUrl: string): Promise<bigint>;
    createGeopoliticsLesson(title: string, content: string, date: Time, dayNumber: bigint): Promise<bigint>;
    createMasterclass(title: string, description: string, instructor: string, duration: bigint): Promise<bigint>;
    createZoomMeeting(title: string, description: string, zoomLink: string, scheduledDate: Time): Promise<bigint>;
    deleteEbook(id: bigint): Promise<void>;
    deleteGeopoliticsLesson(id: bigint): Promise<void>;
    deleteMasterclass(id: bigint): Promise<void>;
    deleteZoomMeeting(id: bigint): Promise<void>;
    enrollInMasterclass(masterclassId: bigint): Promise<void>;
    getAllEbooks(): Promise<Array<Type__3>>;
    getAllGeopoliticsLessons(): Promise<Array<Type__2>>;
    getAllMasterclasses(): Promise<Array<Type__1>>;
    getAllPremiumUsers(): Promise<Array<Principal>>;
    getAllZoomMeetings(): Promise<Array<Type>>;
    getCallerUserRole(): Promise<UserRole>;
    getEbook(id: bigint): Promise<Type__3>;
    getGeopoliticsLesson(id: bigint): Promise<Type__2>;
    getMasterclass(id: bigint): Promise<Type__1>;
    getUserEnrollments(user: Principal): Promise<Array<bigint>>;
    getZoomMeeting(id: bigint): Promise<Type>;
    grantPremium(user: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerPremium(): Promise<boolean>;
    revokePremium(user: Principal): Promise<void>;
    updateEbook(id: bigint, title: string, description: string, author: string, pdfUrl: string): Promise<void>;
    updateGeopoliticsLesson(id: bigint, title: string, content: string, date: Time, dayNumber: bigint): Promise<void>;
    updateMasterclass(id: bigint, title: string, description: string, instructor: string, duration: bigint): Promise<void>;
    updateZoomMeeting(id: bigint, title: string, description: string, zoomLink: string, scheduledDate: Time): Promise<void>;
}
import type { UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEbook(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEbook(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEbook(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createGeopoliticsLesson(arg0: string, arg1: string, arg2: Time, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGeopoliticsLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGeopoliticsLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createMasterclass(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMasterclass(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMasterclass(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createZoomMeeting(arg0: string, arg1: string, arg2: string, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createZoomMeeting(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createZoomMeeting(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteEbook(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEbook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEbook(arg0);
            return result;
        }
    }
    async deleteGeopoliticsLesson(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGeopoliticsLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGeopoliticsLesson(arg0);
            return result;
        }
    }
    async deleteMasterclass(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMasterclass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMasterclass(arg0);
            return result;
        }
    }
    async deleteZoomMeeting(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteZoomMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteZoomMeeting(arg0);
            return result;
        }
    }
    async enrollInMasterclass(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInMasterclass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInMasterclass(arg0);
            return result;
        }
    }
    async getAllEbooks(): Promise<Array<Type__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEbooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEbooks();
            return result;
        }
    }
    async getAllGeopoliticsLessons(): Promise<Array<Type__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGeopoliticsLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGeopoliticsLessons();
            return result;
        }
    }
    async getAllMasterclasses(): Promise<Array<Type__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMasterclasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMasterclasses();
            return result;
        }
    }
    async getAllPremiumUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                return await this.actor.getAllPremiumUsers();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getAllPremiumUsers();
        }
    }
    async getAllZoomMeetings(): Promise<Array<Type>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllZoomMeetings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllZoomMeetings();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEbook(arg0: bigint): Promise<Type__3> {
        if (this.processError) {
            try {
                const result = await this.actor.getEbook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEbook(arg0);
            return result;
        }
    }
    async getGeopoliticsLesson(arg0: bigint): Promise<Type__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeopoliticsLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeopoliticsLesson(arg0);
            return result;
        }
    }
    async getMasterclass(arg0: bigint): Promise<Type__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterclass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterclass(arg0);
            return result;
        }
    }
    async getUserEnrollments(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserEnrollments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserEnrollments(arg0);
            return result;
        }
    }
    async getZoomMeeting(arg0: bigint): Promise<Type> {
        if (this.processError) {
            try {
                const result = await this.actor.getZoomMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZoomMeeting(arg0);
            return result;
        }
    }
    async grantPremium(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.grantPremium(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.grantPremium(arg0);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.isCallerPremium();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.isCallerPremium();
        }
    }
    async revokePremium(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.revokePremium(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.revokePremium(arg0);
        }
    }
    async updateEbook(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEbook(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEbook(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateGeopoliticsLesson(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGeopoliticsLesson(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGeopoliticsLesson(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMasterclass(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMasterclass(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMasterclass(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateZoomMeeting(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateZoomMeeting(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateZoomMeeting(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
